version: '3.1'

services:

  bacula-db-mysql-data:
    images: lizhi/bacula-db-mysql-data:9.2.1
    container_name: bacula-db-mysql-data

  bacula-db-mysql:
    images: lizhi/bacula-db-mysql:9.2.1
    container_name: bacula-db-mysql
    restart: always
    hostname: bacula-db-mysql
    volumes_from:
      - bacula-db-mysql-data:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  bacula-dir:
    images: lizhi/bacula-dir:9.2.1
    container_name: bacula-dir
    hostname: bacula-dir
    ports:
      - "9101:9101" # bconsole ->dir
      - "9102:9102" # dir  ->fd
    extra_hosts:
      - "bacula-fd:127.0.0.1"
    environment:
      - DB_HOST=bacula-db-mysql
    depends_on:
      - bacula-db-mysql
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo "Waiting foe Mysql to be avaulable"
        export  MYSQLPASSWORD="$$MYSQL_ROOT_PASSWORD"
        maxTries=10
        while [ "$$maxTries" -gt 0 ] && ! mysql -h "$$DB_HOST" -U 'root' -c '\l'; do
            sleep 1
        done
        echo 
        if [ "$$maxTries" -le 0 ]; then
            echo >&2 'error:unable to connect Mysql after 10 tries'
            exit 1
        fi

